version: '3'

services:
  db:
    ports:
      - 5432:5432
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
      - postgresql:/usr/lib/postgresql
    networks:
      - main

  pgadmin:
    ports:
      - 8080:80
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
#      To upload bigger files copy them to files folder and than move them to /var/lib/pgadmin/storage for restore. The mapping doesn't work.
      - postgresql:/usr/lib/postgresql
      - ./files:/files
    networks:
      - main


volumes:
  postgresql:
    driver: local
  dbdata:
    driver: local

networks:
  main:
